name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 트리거

jobs:
  deploy:
    runs-on: linux-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # 3. Gradle 빌드
      - name: Build project
        run: |
          ./gradlew clean build -x test

      # 4. EC2로 배포
      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          PEM_FILE: ${{ secrets.EC2_PEM }}
        run: |
          scp -i $PEM_FILE build/libs/*.jar $USER@$HOST:~/app.jar
          ssh -i $PEM_FILE $USER@$HOST "bash ~/deploy.sh"
